exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('species')
    .del()
    .then(function () {
      // Inserts seed entries
      return knex('species').insert([
        {
          "name": "Human",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "caucasian, black, asian, hispanic",
          "hair_colors": "blonde, brown, black, red",
          "eye_colors": "brown, blue, green, hazel, grey, amber",
          "average_lifespan": 120,
          "homeworld_id": 9,
          "language_id": 2,
          "url": "http://swapi.co/api/species/1/"
        }, {
          "name": "Droid",
          "classification_id": 8,
          "designation_id": 1,
          "average_height": 0,
          "skin_colors": "n/a",
          "hair_colors": "n/a",
          "eye_colors": "n/a",
          "average_lifespan": 0,
          "homeworld_id": 1,
          "language_id": 35,
          "url": "http://swapi.co/api/species/2/"
        }, {
          "name": "Wookiee",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 210,
          "skin_colors": "gray",
          "hair_colors": "black, brown",
          "eye_colors": "blue, green, yellow, brown, golden, red",
          "average_lifespan": 400,
          "homeworld_id": 14,
          "language_id": 34,
          "url": "http://swapi.co/api/species/3/"
        }, {
          "name": "Rodian",
          "classification_id": 3,
          "designation_id": 1,
          "average_height": 170,
          "skin_colors": "green, blue",
          "hair_colors": "n/a",
          "eye_colors": "black",
          "average_lifespan": 0,
          "homeworld_id": 23,
          "language_id": 2,
          "url": "http://swapi.co/api/species/4/"
        }, {
          "name": "Hutt",
          "classification_id": 1,
          "designation_id": 1,
          "average_height": 300,
          "skin_colors": "green, brown, tan",
          "hair_colors": "n/a",
          "eye_colors": "yellow, red",
          "average_lifespan": 1000,
          "homeworld_id": 24,
          "language_id": 1,
          "url": "http://swapi.co/api/species/5/"
        }, {
          "name": "Yoda's species",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 66,
          "skin_colors": "green, yellow",
          "hair_colors": "brown, white",
          "eye_colors": "brown, green, yellow",
          "average_lifespan": 900,
          "homeworld_id": 28,
          "language_id": 2,
          "url": "http://swapi.co/api/species/6/"
        }, {
          "name": "Trandoshan",
          "classification_id": 3,
          "designation_id": 1,
          "average_height": 200,
          "skin_colors": "brown, green",
          "hair_colors": "none",
          "eye_colors": "yellow, orange",
          "average_lifespan": 0,
          "homeworld_id": 29,
          "language_id": 3,
          "url": "http://swapi.co/api/species/7/"
        }, {
          "name": "Mon Calamari",
          "classification_id": 4,
          "designation_id": 1,
          "average_height": 160,
          "skin_colors": "red, blue, brown, magenta",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 0,
          "homeworld_id": 31,
          "language_id": 4,
          "url": "http://swapi.co/api/species/8/"
        }, {
          "name": "Ewok",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 100,
          "skin_colors": "brown",
          "hair_colors": "white, brown, black",
          "eye_colors": "orange, brown",
          "average_lifespan": 0,
          "homeworld_id": 7,
          "language_id": 5,
          "url": "http://swapi.co/api/species/9/"
        }, {
          "name": "Sullustan",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "pale",
          "hair_colors": "none",
          "eye_colors": "black",
          "average_lifespan": 0,
          "homeworld_id": 33,
          "language_id": 6,
          "url": "http://swapi.co/api/species/10/"
        }, {
          "name": "Neimodian",
          "classification_id": 5,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "grey, green",
          "hair_colors": "none",
          "eye_colors": "red, pink",
          "average_lifespan": 0,
          "homeworld_id": 18,
          "language_id": 7,
          "url": "http://swapi.co/api/species/11/"
        }, {
          "name": "Gungan",
          "classification_id": 4,
          "designation_id": 1,
          "average_height": 190,
          "skin_colors": "brown, green",
          "hair_colors": "none",
          "eye_colors": "orange",
          "average_lifespan": 0,
          "homeworld_id": 8,
          "language_id": 8,
          "url": "http://swapi.co/api/species/12/"
        }, {
          "name": "Toydarian",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 120,
          "skin_colors": "blue, green, grey",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 91,
          "homeworld_id": 34,
          "language_id": 9,
          "url": "http://swapi.co/api/species/13/"
        }, {
          "name": "Dug",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 100,
          "skin_colors": "brown, purple, grey, red",
          "hair_colors": "none",
          "eye_colors": "yellow, blue",
          "average_lifespan": 0,
          "homeworld_id": 35,
          "language_id": 10,
          "url": "http://swapi.co/api/species/14/"
        }, {
          "name": "Twi'lek",
          "classification_id": 6,
          "designation_id": 1,
          "average_height": 200,
          "skin_colors": "orange, yellow, blue, green, pink, purple, tan",
          "hair_colors": "none",
          "eye_colors": "blue, brown, orange, pink",
          "average_lifespan": 0,
          "homeworld_id": 37,
          "language_id": 11,
          "url": "http://swapi.co/api/species/15/"
        }, {
          "name": "Aleena",
          "classification_id": 3,
          "designation_id": 1,
          "average_height": 80,
          "skin_colors": "blue, gray",
          "hair_colors": "none",
          "eye_colors": "unknown",
          "average_lifespan": 79,
          "homeworld_id": 38,
          "language_id": 12,
          "url": "http://swapi.co/api/species/16/"
        }, {
          "name": "Vulptereen",
          "classification_id": 5,
          "designation_id": 1,
          "average_height": 100,
          "skin_colors": "grey",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 0,
          "homeworld_id": 39,
          "language_id": 13,
          "url": "http://swapi.co/api/species/17/"
        }, {
          "name": "Xexto",
          "classification_id": 5,
          "designation_id": 1,
          "average_height": 125,
          "skin_colors": "grey, yellow, purple",
          "hair_colors": "none",
          "eye_colors": "black",
          "average_lifespan": 0,
          "homeworld_id": 40,
          "language_id": 14,
          "url": "http://swapi.co/api/species/18/"
        }, {
          "name": "Toong",
          "classification_id": 5,
          "designation_id": 1,
          "average_height": 200,
          "skin_colors": "grey, green, yellow",
          "hair_colors": "none",
          "eye_colors": "orange",
          "average_lifespan": 0,
          "homeworld_id": 41,
          "language_id": 15,
          "url": "http://swapi.co/api/species/19/"
        }, {
          "name": "Cerean",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 200,
          "skin_colors": "pale pink",
          "hair_colors": "red, blond, black, white",
          "eye_colors": "hazel",
          "average_lifespan": 0,
          "homeworld_id": 43,
          "language_id": 16,
          "url": "http://swapi.co/api/species/20/"
        }, {
          "name": "Nautolan",
          "classification_id": 4,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "green, blue, brown, red",
          "hair_colors": "none",
          "eye_colors": "black",
          "average_lifespan": 70,
          "homeworld_id": 44,
          "language_id": 17,
          "url": "http://swapi.co/api/species/21/"
        }, {
          "name": "Zabrak",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "pale, brown, red, orange, yellow",
          "hair_colors": "black",
          "eye_colors": "brown, orange",
          "average_lifespan": 0,
          "homeworld_id": 45,
          "language_id": 18,
          "url": "http://swapi.co/api/species/22/"
        }, {
          "name": "Tholothian",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 0,
          "skin_colors": "dark",
          "hair_colors": "unknown",
          "eye_colors": "blue, indigo",
          "average_lifespan": 0,
          "homeworld_id": 46,
          "language_id": 19,
          "url": "http://swapi.co/api/species/23/"
        }, {
          "name": "Iktotchi",
          "classification_id": 5,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "pink",
          "hair_colors": "none",
          "eye_colors": "orange",
          "average_lifespan": 0,
          "homeworld_id": 47,
          "language_id": 20,
          "url": "http://swapi.co/api/species/24/"
        }, {
          "name": "Quermian",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 240,
          "skin_colors": "white",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 86,
          "homeworld_id": 48,
          "language_id": 21,
          "url": "http://swapi.co/api/species/25/"
        }, {
          "name": "Kel Dor",
          "classification_id": 5,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "peach, orange, red",
          "hair_colors": "none",
          "eye_colors": "black, silver",
          "average_lifespan": 70,
          "homeworld_id": 49,
          "language_id": 22,
          "url": "http://swapi.co/api/species/26/"
        }, {
          "name": "Chagrian",
          "classification_id": 4,
          "designation_id": 1,
          "average_height": 190,
          "skin_colors": "blue",
          "hair_colors": "none",
          "eye_colors": "blue",
          "average_lifespan": 0,
          "homeworld_id": 50,
          "language_id": 23,
          "url": "http://swapi.co/api/species/27/"
        }, {
          "name": "Geonosian",
          "classification_id": 7,
          "designation_id": 1,
          "average_height": 178,
          "skin_colors": "green, brown",
          "hair_colors": "none",
          "eye_colors": "green, hazel",
          "average_lifespan": 0,
          "homeworld_id": 11,
          "language_id": 24,
          "url": "http://swapi.co/api/species/28/"
        }, {
          "name": "Mirialan",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "yellow, green",
          "hair_colors": "black, brown",
          "eye_colors": "blue, green, red, yellow, brown, orange",
          "average_lifespan": 0,
          "homeworld_id": 51,
          "language_id": 25,
          "url": "http://swapi.co/api/species/29/"
        }, {
          "name": "Clawdite",
          "classification_id": 3,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "green, yellow",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 70,
          "homeworld_id": 54,
          "language_id": 26,
          "url": "http://swapi.co/api/species/30/"
        }, {
          "name": "Besalisk",
          "classification_id": 4,
          "designation_id": 1,
          "average_height": 178,
          "skin_colors": "brown",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 75,
          "homeworld_id": 55,
          "language_id": 27,
          "url": "http://swapi.co/api/species/31/"
        }, {
          "name": "Kaminoan",
          "classification_id": 4,
          "designation_id": 1,
          "average_height": 220,
          "skin_colors": "grey, blue",
          "hair_colors": "none",
          "eye_colors": "black",
          "average_lifespan": 80,
          "homeworld_id": 10,
          "language_id": 28,
          "url": "http://swapi.co/api/species/32/"
        }, {
          "name": "Skakoan",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 0,
          "skin_colors": "grey, green",
          "hair_colors": "none",
          "eye_colors": "unknown",
          "average_lifespan": 0,
          "homeworld_id": 56,
          "language_id": 29,
          "url": "http://swapi.co/api/species/33/"
        }, {
          "name": "Muun",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 190,
          "skin_colors": "grey, white",
          "hair_colors": "none",
          "eye_colors": "black",
          "average_lifespan": 100,
          "homeworld_id": 57,
          "language_id": 30,
          "url": "http://swapi.co/api/species/34/"
        }, {
          "name": "Togruta",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 180,
          "skin_colors": "red, white, orange, yellow, green, blue",
          "hair_colors": "none",
          "eye_colors": "red, orange, yellow, green, blue, black",
          "average_lifespan": 94,
          "homeworld_id": 58,
          "language_id": 31,
          "url": "http://swapi.co/api/species/35/"
        }, {
          "name": "Kaleesh",
          "classification_id": 3,
          "designation_id": 1,
          "average_height": 170,
          "skin_colors": "brown, orange, tan",
          "hair_colors": "none",
          "eye_colors": "yellow",
          "average_lifespan": 80,
          "homeworld_id": 59,
          "language_id": 32,
          "url": "http://swapi.co/api/species/36/"
        }, {
          "name": "Pau'an",
          "classification_id": 2,
          "designation_id": 1,
          "average_height": 190,
          "skin_colors": "grey",
          "hair_colors": "none",
          "eye_colors": "black",
          "average_lifespan": 700,
          "homeworld_id": 12,
          "language_id": 33,
          "url": "http://swapi.co/api/species/37/"
        }, {
          "name": "Umbaran",
          "classification_id": 2,
          "designation_id": 1,
          "homeworld_id": 45,
          "language_id": 2,
        }
      ]);
    });
};
